### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by agconti** [agconti/fsr#27]
# UI Styling
- [x] Add video background for home screen #16
- [x] Style sign in button to meet FourSquare requirements. #17
- [ ] 'Black List' venuelikes from available lists #25
- [x] Add venue cross streets back in #30
- [x] Style tips list #29
- [ ] Fade Children Elements in on load #28
- [x] Add normalize.css #32
- [ ] Attribute to Foursquare #33
- [ ] Update dependencies #40
