### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by agconti** [agconti/fsr#8]
# Choice UI
- [x] Allow user to 'spin again' #5
- [x] Display chosen venue to user #4
- [x] Integrate angular material #9
- [x] Get top tips for each location #19
